# Generated by Django 4.2.14 on 2024-07-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_memo_openai_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='parameter',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memo',
            name='openai_response',
            field=models.TextField(default='na'),
            preserve_default=False,
        ),
    ]
