# Generated by Django 4.2.14 on 2024-07-21 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_memo_parameter_alter_memo_openai_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='openai_response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
