# Generated by Django 4.2.14 on 2024-07-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_alter_memo_openai_response'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memo',
            name='content',
        ),
        migrations.RemoveField(
            model_name='memo',
            name='openai_response',
        ),
        migrations.AddField(
            model_name='memo',
            name='conversation',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
