# Generated by Django 4.2.14 on 2024-07-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_remove_memo_content_remove_memo_openai_response_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='memo',
            name='thread_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
